export default {
  EMAIL_PLACEHOLDER: 'Email',
  PASSWORD_PLACEHOLDER: 'Password',
  SIGN_IN: 'Sign in',
  CREATE_AN_ACCOUNT: 'Create account',
  OR: 'Or',
  TWITTER: 'Twitter',
  GOOGLE: 'Google',
  SIGNUP_WITH_EMAIL: 'Sign up with Email',
  NONE: 'none',
  FIRST_NAME_PLACEHOLDER: 'First name',
  LAST_NAME_PLACEHOLDER: 'Last name',
  CONFIRM_PASSWORD_PLACEHOLDER: 'Confirm password',
  BOARD_TITLE: 'Board',
  PATIENT_LIST_TITLE: 'Patient List',
  SCHEDULE_TITLE: 'Schedule',
  UPCOMING_AVAILABILITY_TITLE: 'Upcoming Availability',
  SETTINGS_TITLE: 'Settings',
  PRIVACY_TERMS_TITLE: 'Privacy & Terms',
  LOGOUT_TITLE: 'Logout',
  CALL_999: 'Call 999',
  CALL_SUPPORT: 'Call Support',
  MARK_ALL_READ_TITLE: 'Mark all as read',
  HEADER_PENDING: 'Pending',
  HEADER_TO_SCHEDULE: 'To Schedule',
  REQUIREMENTS_HEADER_TITLE: 'Requirements:',
  CALL_PATIENT_BTN_TITLE: 'Call Patient',
  NOTES_BTN_TITLE: 'Notes',
  COMPLETE_TO_PROCEED: 'Complete to proceed',
  NOTES_HEADER_TITLE: 'Notes',
  NOTES_STRING: 'Consultation notes',
  ENTER_NOTES: 'Enter notes...',
  COMPLETE_BTN_TITLE: 'Complete',
  DISCOVERY_SETTINGS: 'Discovery Settings',
  NOTIFICATIONS: 'Notifications',
  PAYMENT_METHODS: 'Payment methods',
  PROFILE: 'Profile',
  PUSH_NOTIFICATIONS: 'Push notifications',
  TEST_MESSAGE_NOTIFICATIONS: 'Text message notifications',
  MESSAGES: 'Messages',
  FROM_FRIENDS: 'From friends',
  ACCOUNT_ACTIVITY: 'Account Activity',
  CHANGES_MADE: 'Changes made to your account',
  PRODUCT_ANNOUNCEMENTS: 'Product Announcements',
  FEATURE_UPDATE: 'Feature update and more',
  LOCATION: 'Location',
  DISTANCE: 'Distance',
  REQUIREMENTS_TITLE: 'Requirements',
  BASIC_PROFILE: 'BASIC PROFILE',
  PRIVATE_INFORMATION: 'PRIVATE INFORMATION',
  CHANGE_PASSWORD: 'Change Password',
  GENERAL_AVAILABILITY_HEADER_TITLE: 'General Availability',
  ENTER_NEW_PASSWORD: 'Enter New Password',
  CAMERA: 'Camera',
  PHOTO_LIBRARY: 'Photo Library',
  ACCEPT_BTN_TITLE: 'Accept',
  REJECT_BTN_TITLE: 'Reject',
  SCHEDULE_APPOINTMENT_BTN_TITLE: 'Schedule',
  PENDING_HEADER_TITLE: 'Pending',
  SCHEDULE_HEADER_TITLE: 'To Schedule',
  INVALID_EMAIL_ID_MSG: 'Please enter a valid Email ID.',
  EMPTY_DYNAMIC_SELECTED_INPUT_FEILDS: 'Please fill in all selected empty fields.',
  ENTER_VALUE_IN_TEXT: 'Please enter value in',
  OR_UNSELECT_IT_TEXT: 'or unselect it.',
  EMPTY_PASSWORD_MSG: 'Please enter password.',
  PASSWORD_CONFIRM_PASSWORD_NOT_MATCH_MSG: 'Password and confirm password not match.',
  EMPTY_FIRST_NAME: 'Please enter first name.',
  MSG_INTERNET_CONNECTION_ERROR:
    'Your internet connection has got lost or is poor. Please try again.',
  PASSWORD_LENGTH_VALIDATION: 'Please enter at least 8 characters.',
  PASSWORD_UPPERCASE_VALIDATION: 'Please enter at least one UPPERCASE letter.',
  PASSWORD_LOWERCASE_VALIDATION: 'Please enter at least one lowercase letter.',
  PASSWORD_NUMBER_VALIDATION: 'Please enter at least one number.',
  PASSWORD_SPECIAL_CHARACTER_VALIDATION: 'Please enter at least one special character.',
  NEW_USER: 'New User? ',
  REGISTER_NOW: 'Register Now',
  FORGOT_PASSWORD: 'Forgot Password?',
  ALREADY_HAVE_AN_ACCOUNT: 'Already have an account? ',
  REQUEST_BTN_TITLE: 'Request',
  PATIENT_HEADING: 'Patient: ',
  REQUIRES_HEADING: 'Requires: ',
  AGE_HEADING: 'Age: ',
  ADDRESS_HEADING: 'Address: ',
  PROVIDER_HEADING: 'Provider: ',
  PRACTICE_PATIENT_BOARD_STR: 'Practice patient within',
  MILES_STR: 'miles',
  YEAR_OLD_STR: 'y/o',
  NO_DATA_FOUND_TITLE: 'No data found!',
  BOARD_EMPTY_LIST_MSG: "There are no items in list yet, so we don't have anything to show you.",
  ASSESSMENTS_SCREEN_NAV_TITLE: 'Assessments',
  NEW_FULLFILLMENTS_SCREEN_NAV_TITLE: 'New Fullfillments',
  SCHEDULE_TAB_1_TITLE: 'Pending',
  SCHEDULE_TAB_2_TITLE: 'To Schedule',
  APPOINTMENT_NOTES_LABEL: 'Appointment Notes',
  SKILL_TITLE_PLACEHOLDER_TEXT: 'Enter skill title',
  METRICS_TITLE_PLACEHOLDER_TEXT: 'Enter metrics title',
  SKILL_DETAILS_HEADING_TEXT: 'Skill Details',
  METRICS_DETAILS_HEADING_TEXT: 'Metrics Details',
  BUTTON_ADD_FULLFILLMENTS_TEXT: 'Add Fullfillment',
  SKILL_TITLE_EMPTY_ERR_MSG: 'Please enter the skill title.',
  METRICS_TITLE_EMPTY_ERR_MSG: 'Please enter the metrics title.',
  PLACEHOLDER_TEXT_SEARCH_WITH_DOTS: 'Search...',
  EMPTY_DYNAMIC_INPUT_UNSELECTED_FEILDS:
    'Please fill in values and select the fields of your choice.',
  APPOINTMENT_ID_NOT_FOUND: 'Appointment id not found in patient data.',
  SCHEDULED_TITLE: 'Scheduled',
  NOT_AVAILABLE_TITLE: 'Not available',
  AVAILABLE_TITLE: 'Available',
  OLD_PASSWORD_PLACEHOLDER: 'Old password',
  NEW_PASSWORD_PLACEHOLDER: 'New password',
  CONFIRM_NEW_PASSWORD_PLACEHOLDER: 'Confirm new password',
  UPDATE_BTN_TITLE: 'Update',

  /* Date formats */
  DFM_BOARD_PATIENT_DOB: 'YYYY-MM-DD',
  DFM_PATIENT_LIST_HEADER_DATE: 'YYYY-MM-DD',
  DFM_PATIENT_LIST_CALENDAR_SELECTION_DATE: 'YYYY-MM-DD',
  DFM_SCHEDULE_DATE: 'Do MMM YYYY',
};
