export default {
  LOGIN_URL: 'account/login/',
  SIGNUP_URL: 'account/register/',
  BOARD_LIST_URL: 'patients/board/',
  SCHEDULE_LIST_URL: 'patients/schedule/',
  UPCOMING_PATIENT_LIST_URL: 'patients/upcoming/',
  BOARD_APPOINTMENT_ACCEPT_URL: 'board_accept_appointment/',
  BOARD_APPOINTMENT_REJECT_URL: 'board_decline_appointment/',
  SCHEDULE_APPOINTMENT_ACCEPT_URL: 'schedule_accept_appointment/',
  SCHEDULE_APPOINTMENT_REJECT_URL: 'schedule_decline_appointment/',
  NEW_FULLFILLMENTS_SEARCH_QUERY_URL: 'fullfillments/?value=',
  COMPLETE_APPOINTMENT_URL: 'complete_appointment/',
  GET_GENERAL_AVAILABILITY_URL: 'get_general_availability/',
  GET_UPCOMING_AVAILABILITY_URL: 'get_upcoming_availability/',
};
